Repository nhnacademy-be10-1lluwa/bookstore-order-service, pull requests merged in 2025-07, with the labels that each got.

#230 Feature: #229 비회원 주문하기 구현
  pom.xml
  src/main/java/com/nhnacademy/illuwa/common/external/user/UserApiClient.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/guest/GuestOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/dto/order/guest/GuestCreateRequest.java
  src/main/java/com/nhnacademy/illuwa/domain/order/dto/order/guest/GuestCreateResponse.java
  src/main/java/com/nhnacademy/illuwa/domain/order/dto/order/guest/GuestOrderInitDirectResponseDto.java
  src/main/java/com/nhnacademy/illuwa/domain/order/dto/order/guest/GuestOrderRequestDirect.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/OrderService.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/order/util/generator/NumberGenerator.java
Labels: ♻️ refactor, ⚙️ chore, 💫FEAT

#237 feat: #231 회원 장바구니 주문 구현
  src/main/java/com/nhnacademy/illuwa/common/external/product/ProductApiClient.java
  src/main/java/com/nhnacademy/illuwa/common/external/product/dto/BookCartResponse.java
  src/main/java/com/nhnacademy/illuwa/common/external/product/dto/CartOrderItemDto.java
  src/main/java/com/nhnacademy/illuwa/common/external/product/dto/CartResponse.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/user/MemberOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/dto/order/member/MemberOrderInitFromCartResponseDto.java
  src/main/java/com/nhnacademy/illuwa/domain/order/dto/order/member/MemberOrderRequest.java
  src/main/java/com/nhnacademy/illuwa/domain/order/factory/MemberOrderCartFactory.java
  src/main/java/com/nhnacademy/illuwa/domain/order/factory/MemberOrderDirectFactory.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/impl/OrderServiceImpl.java
Labels: ♻️ refactor, 💫FEAT

#236 [FEAT] 해당 도서,카테고리ID를 기준으로 사용가능한 쿠폰 조회
  http/request.http
  order-service.iml
  src/main/java/com/nhnacademy/illuwa/domain/coupons/controller/MemberCouponController.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/dto/memberCoupon/MemberCouponDto.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/repository/custom/CouponMemberQuerydslRepository.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/repository/impl/MemberCouponRepositoryImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/service/MemberCouponService.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/service/impl/MemberCouponServiceImpl.java
Labels: 💫FEAT

#243 feat: #238 회원 쿠폰 적용 - 사용은 미처리
  src/main/java/com/nhnacademy/illuwa/domain/coupons/controller/MemberCouponController.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/dto/memberCoupon/MemberCouponDiscountDto.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/dto/memberCoupon/MemberCouponDto.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/factory/DiscountCalculator.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/repository/custom/CouponMemberQuerydslRepository.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/repository/impl/MemberCouponRepositoryImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/service/MemberCouponService.java
  src/main/java/com/nhnacademy/illuwa/domain/coupons/service/impl/MemberCouponServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/user/MemberOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/dto/order/member/MemberOrderInitDirectResponseDto.java
  src/main/java/com/nhnacademy/illuwa/domain/order/dto/order/member/MemberOrderInitFromCartResponseDto.java
  src/main/java/com/nhnacademy/illuwa/domain/order/factory/GuestOrderDirectFactory.java
  src/main/java/com/nhnacademy/illuwa/domain/order/factory/MemberOrderCartFactory.java
  src/main/java/com/nhnacademy/illuwa/domain/order/factory/MemberOrderDirectFactory.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/impl/OrderServiceImpl.java
Labels: 💫FEAT

#248 feat: #247 회원 등급 재조정 로직 변경
  http/guestOrderRequest.http
  src/main/java/com/nhnacademy/illuwa/common/external/user/dto/MemberGradeUpdateRequest.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/common/CommonOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/repository/impl/OrderRepositoryImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/MemberGradeService.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/impl/MemberGradeServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/impl/OrderServiceImpl.java
Labels: 💫FEAT

#258 feat: #257 환불 로직 추가
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/guest/GuestOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/entity/types/OrderStatus.java
Labels: 💫FEAT

#261 refactor: 컨트롤러 코드 수정
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/user/MemberOrderController.java
Labels: 💫FEAT

#266 Feature: #265 awaiting order delete
  http/guestOrderRequest.http
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/admin/AdminOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/common/CommonOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/entity/Order.java
  src/main/java/com/nhnacademy/illuwa/domain/order/repository/OrderRepository.java
  src/main/java/com/nhnacademy/illuwa/domain/order/repository/custom/OrderQuerydslRepository.java
  src/main/java/com/nhnacademy/illuwa/domain/order/repository/impl/OrderRepositoryImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/AdminUtilsService.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/MemberGradeService.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/impl/AdminUtilsServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/impl/MemberGradeServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/order/util/scheduler/DbDataScheduler.java
  src/main/java/com/nhnacademy/illuwa/domain/order/util/scheduler/MonthlyNetOrderAmountScheduler.java
Labels: 💫FEAT

#272 refactor: 코드 리팩토링
  http/guestOrderRequest.http
  pom.xml
  src/main/java/com/nhnacademy/illuwa/OrderServiceApplication.java
  src/main/java/com/nhnacademy/illuwa/domain/order/batch/config/MemberGradeJobConfig.java
  src/main/java/com/nhnacademy/illuwa/domain/order/batch/config/OrderCleanUpJopConfig.java
  src/main/java/com/nhnacademy/illuwa/domain/order/batch/config/ReaderConfig.java
  src/main/java/com/nhnacademy/illuwa/domain/order/batch/domain/MemberNetOrderAgg.java
  src/main/java/com/nhnacademy/illuwa/domain/order/batch/processor/MemberGradeProcessor.java
  src/main/java/com/nhnacademy/illuwa/domain/order/batch/scheduler/BatchScheduler.java
  src/main/java/com/nhnacademy/illuwa/domain/order/batch/writer/MemberGradeWriter.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/admin/AdminOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/admin/BatchTriggerController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/factory/AbstractOrderFactory.java
  src/main/java/com/nhnacademy/illuwa/domain/order/repository/OrderRepository.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/impl/OrderServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/order/util/scheduler/DbDataScheduler.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/OrderServiceTest.java
Labels: 💫FEAT

#290 refactor: 환불 로직 수정
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/admin/AdminOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/common/CommonOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/guest/GuestOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/factory/GuestOrderDirectFactory.java
Labels: ♻️ refactor, 💫FEAT

#300 Feature/299 edit api address
  src/main/java/com/nhnacademy/illuwa/common/external/user/UserApiClient.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/admin/AdminOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/admin/BatchTriggerController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/admin/PackagingController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/common/CommonOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/guest/GuestOrderController.java
  src/main/java/com/nhnacademy/illuwa/domain/order/controller/user/MemberOrderController.java
Labels: ♻️ refactor

#301 Feature/295 service layer test code
  src/main/java/com/nhnacademy/illuwa/domain/order/dto/order/OrderResponseDto.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/admin/impl/AdminUtilsServiceImpl.java
  src/main/java/com/nhnacademy/illuwa/domain/order/service/common/impl/CommonOrderServiceImpl.java
  src/test/java/com/nhnacademy/illuwa/domain/order/controller/PackagingControllerTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/controller/ShippingPolicyControllerTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/controller/admin/AdminOrderControllerTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/controller/admin/PackagingControllerTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/controller/admin/ShippingPolicyControllerTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/AddReturnRequestTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/OrderItemServiceTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/OrderServiceTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/ReturnRequestServiceTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/ShippingPolicyServiceTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/admin/AdminOrderServiceTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/admin/AdminUtilsServiceTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/common/CommonOrderServiceTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/guest/GuestOrderServiceTest.java
  src/test/java/com/nhnacademy/illuwa/domain/order/service/member/MemberOrderServiceTest.java
Labels: ✅ test
